/**
 * Projects from charlottekellycopy.com.
 *
 * Everything below except the hero `image`, `role` and Fulton's v2 fields
 * is Charlotte's own, scraped from her project pages on the current site:
 * the services line, the case-study copy with its links, the gallery, and
 * the credits, now split into `agency` and `team`. Gallery images are copies in /public/work/<slug>/, numbered in the
 * order her pages show them; their dimensions are measured from the files.
 * The hero `image` is the portfolio thumbnail already in /public.
 *
 * From phase 4 onward the same shape comes out of Sanity, where every image
 * carries its own required alt text. Until then the templates fall back to
 * the project title for alt, which is a stand-in, not real alt text — her
 * site has none to copy.
 */

/**
 * A run of body copy. A plain string is text; an object is an inline link.
 *
 * Deliberately not markdown: the copy needs exactly one inline element (a
 * link), and an array of runs gives that without shipping a parser, while
 * mapping cleanly onto Portable Text when Sanity lands in phase 4.
 */
export type BodyRun = string | { text: string; href: string };

export type Project = {
  slug: string;
  title: string;
  services: string;
  image: string;
  /**
   * v3's background while this project is open: a pale tint of the hue that
   * covers most of its thumbnail, at a lightness that keeps black text around
   * 16:1. Generated by sampling the image, not chosen — Fulton's is set by
   * hand to its site's blue, because its thumbnail is mostly boardwalk.
   */
  tint: string;
  /** The first sentence of her case-study copy, for v3's list. */
  summary: string;
  /** Case-study copy: one array of runs per paragraph. */
  body: BodyRun[][];
  /** Case-study images, at their own proportions. */
  gallery: { src: string; width: number; height: number }[];
  /** The gallery image a case study opens on, where the widest one (see
      heroOf) is not the one to lead with. */
  hero?: string;
  /** Her part in it, shown as "Role". Drafted from her copy for her to
      confirm — her site has no such field. Fulton's is the mock's. */
  role: string[];
  /** The agency or studio she worked with, as she credits them. Her site
      labels some studios by what they did ("Creative direction: Formal
      Studio"); here every one is an Agency or a Studio. */
  agency: { kind: "Agency" | "Studio"; name: string; href?: string };
  /** Anyone else she credits by name: "Web design: No Ideas". Only some
      projects have one. */
  team?: { role: string; name: string; href?: string }[];

  /* The slots below feed v2's case-study template, and only Fulton fills
     them, from the mock. A project without them keeps its title and
     services, and a slot with nothing to fill it is left out. `line` is not
     shown at the moment — v2's latest layout dropped it — but it is her
     copy, so it is kept. */

  /** What the client makes, in about five words. */
  descriptor?: string;
  /** The line she wrote that positions the brand. */
  line?: string;
  /** The deliverables, grouped in the order the work happened. Falls back to
      `services` as a single group. */
  scope?: { title: string; items: string[] }[];
};

export const PROJECTS: Project[] = [
  {
    slug: "snackville-at-pacific-park",
    title: "Snackville at Pacific Park",
    services: "Naming • messaging • brand guidelines",
    image: "/snackville.webp",
    tint: "oklch(91% 0.036 66)",
    summary: "Welcome to Snackville at Pacific Park, the reimagined food court at the iconic Santa Monica Pier in Los Angeles.",
    body: [
      [
        "Welcome to ",
        { text: "Snackville at Pacific Park", href: "https://pacpark.com/snackville/" },
        ", the reimagined food court at the iconic Santa Monica Pier in Los Angeles. On the menu at Snackville: sweet treats, tasty bites, cold drinks, and more.",
      ],
      [
        "Working with a creative team assembled and led by NYC studio ",
        { text: "Zan Inc", href: "https://www.zangoodman.com/" },
        ", we named Snackville and its five new food concepts, each with a standalone look and feel. I also created messaging for menus, swag, and signage and polished the brand guidelines. Now the fun and neon nostalgia people love about the pier is on offer at its food court, too.",
      ],
    ],
    gallery: [
      { src: "/work/snackville-at-pacific-park/01.jpg", width: 1920, height: 1080 },
      { src: "/work/snackville-at-pacific-park/02.jpg", width: 1920, height: 2879 },
      { src: "/work/snackville-at-pacific-park/03.jpg", width: 1920, height: 2878 },
      { src: "/work/snackville-at-pacific-park/04.jpg", width: 1920, height: 1536 },
      { src: "/work/snackville-at-pacific-park/05.jpg", width: 1920, height: 1281 },
      { src: "/work/snackville-at-pacific-park/06.jpg", width: 1920, height: 2879 },
      { src: "/work/snackville-at-pacific-park/07.jpg", width: 1920, height: 1281 },
    ],
    role: ["Naming", "Copy"],
    agency: { kind: "Studio", name: "Zan Inc.", href: "https://www.zangoodman.com/" },
  },
  {
    slug: "nutrire",
    title: "Nutrire",
    services: "Creative concepts • product naming • packaging • verbal identity • messaging",
    image: "/NUTRIRE.webp",
    tint: "oklch(91% 0.032 64)",
    summary: "Nutrire is a line of haircare products founded on the principle that healthier hair begins with a nourished scalp.",
    body: [
      [
        "Nutrire is a line of haircare products founded on the principle that healthier hair begins with a nourished scalp. Crafted by Chicago-based powerhouse Mario Tricoci, it offers a highly tailored routine targeting both skin and hair needs. Shampoos address the scalp; conditioners tend to the strand.",
      ],
      [
        "I worked with the team at Established to build Nutrire from the ground up. We started with creative concepts, ultimately balancing the formulas’ technical precision with romance through a territory we called “Garden Rhapsody.” My work included product naming, packaging copy, and key messaging for launch, plus a light touch on tone of voice for brand guidelines.",
      ],
      [
        "Established’s work on Nutrire received a Gold Pentaward; see more ",
        { text: "here", href: "https://establishednyc.com/nutrire" },
        ".",
      ],
    ],
    gallery: [
      { src: "/work/nutrire/01.jpg", width: 2500, height: 1667 },
      { src: "/work/nutrire/02.jpg", width: 2500, height: 1461 },
      { src: "/work/nutrire/03.jpg", width: 2500, height: 1665 },
      { src: "/work/nutrire/04.jpg", width: 1299, height: 1299 },
      { src: "/work/nutrire/05.jpg", width: 1726, height: 1033 },
    ],
    role: ["Concepts", "Naming", "Copy"],
    agency: { kind: "Agency", name: "Established", href: "https://establishednyc.com/" },
  },
  {
    slug: "rux",
    title: "RUX",
    services: "Naming • verbal identity • site copy • brand story • messaging • brand guidelines",
    image: "/RUX_16.webp",
    tint: "oklch(91% 0.049 62)",
    summary: "RUX, formerly Open Door Technology, builds enterprise resource planning (ERP) software systems for construction and equipment rental businesses.",
    body: [
      [
        "RUX, formerly Open Door Technology, builds enterprise resource planning (ERP) software systems for construction and equipment rental businesses. Unlike competitors with one-size-fits-all solutions, RUX tailors and unites business applications to create flexible systems with serious longevity. It came to design studio ",
        { text: "Company Policy", href: "https://www.companypolicy.studio/" },
        " for a full rebrand, including naming, strategy, and design, aiming to stand out as the clear leader in a crowded yet aesthetically homogeneous space.",
      ],
      [
        "I crafted a confident tone of voice for RUX, leaning into declarative messaging and a feeling of earned sturdiness, and solidified short and long versions of the brand’s narrative. I translated this work into copy for the new RUX site, which the talented crew at Company Policy also designed. You can see more from the studio ",
        { text: "here", href: "https://www.companypolicy.studio/work/rux" },
        ".",
      ],
    ],
    gallery: [
      { src: "/work/rux/01.png", width: 800, height: 936 },
      { src: "/work/rux/02.png", width: 1291, height: 718 },
      { src: "/work/rux/03.png", width: 1295, height: 720 },
    ],
    role: ["Naming", "Copy"],
    agency: { kind: "Studio", name: "Company Policy", href: "https://www.companypolicy.studio/" },
  },
  {
    slug: "fulton",
    title: "Fulton",
    services: "Verbal identity • messaging • brand story • blogs • packaging • site copy",
    image: "/fulton.webp",
    tint: "oklch(91% 0.045 250)",
    summary: "Fulton designs sustainable modern cork insoles.",
    body: [
      [
        "Fulton designs sustainable modern cork insoles. It was founded to help people take control of their alignment from the ground up, mitigating the impact of unsupportive shoes and natural variations of the foot. The brand partnered with ",
        { text: "Formal Studio", href: "https://formal-studio.com/" },
        " to create its identity from scratch: everything from strategic foundations to a brand new site.",
      ],
      [
        "Our work started with the insight that arch support should be a proactive step toward full-body wellness, positioning Fulton as a daily essential for active people—“a better way to walk.” From there, I developed Fulton’s story, key messaging, and a relatable, optimistic voice. I also wrote site, packaging, and blog copy for Fulton’s launch. Custom arch support was always comfortable and cushy. Now it’s cool.",
      ],
    ],
    gallery: [
      { src: "/work/fulton/01.png", width: 750, height: 421 },
      { src: "/work/fulton/02.png", width: 750, height: 420 },
      { src: "/work/fulton/03.png", width: 750, height: 402 },
      { src: "/work/fulton/04.png", width: 750, height: 397 },
      { src: "/work/fulton/05.png", width: 750, height: 446 },
      { src: "/work/fulton/06.jpg", width: 750, height: 422 },
      { src: "/work/fulton/07.gif", width: 800, height: 1200 },
      { src: "/work/fulton/08.gif", width: 1530, height: 2294 },
      { src: "/work/fulton/09.png", width: 499, height: 754 },
    ],
    role: ["Copy", "Strategy"],
    agency: { kind: "Studio", name: "Formal Studio", href: "https://formal-studio.com/" },
    team: [
      { role: "Web design", name: "No Ideas", href: "https://noideas.website/" },
    ],
    descriptor: "Sustainable modern cork insoles",
    line: "A better way to walk.",
    scope: [
      { title: "Foundations", items: ["Brand story", "messaging", "voice"] },
      { title: "Launch copy", items: ["Site", "packaging", "blogs"] },
    ],
  },
  {
    slug: "eez-co",
    title: "EEZ Co.",
    services: "Verbal identity • brand story • messaging",
    image: "/eez.webp",
    tint: "oklch(91% 0.055 152)",
    summary: "EEZ Co. are suckers for less-sucky sick days: lollipops and drops with organic ingredients to remedy coughs, sniffles, and more.",
    body: [
      [
        "EEZ Co. are suckers for less-sucky sick days: lollipops and drops with organic ingredients to remedy coughs, sniffles, and more. Originally called “Momeez Choice,” the brand came to ",
        { text: "Brains", href: "https://www.brains.co/" },
        " for a full rebrand to propel it from a word-of-mouth favorite (already available in 35k+ stores!) to a family wellness leader. It needed a new name, a snappier voice, and updated messaging to match a fresher poppier look.",
      ],
      [
        "I worked with the Brains team to define how EEZ Co. sounds, articulate its mission and story, and create a bank of headlines to inspire web and social copy. With plenty of room to play, we landed on a precocious, lighthearted tone of voice to support parents on those particularly tough days and make it all just a touch… easier.",
      ],
      [
        "For more, Brains has a full overview of the project ",
        { text: "here", href: "https://www.brains.co/work/eez-co" },
        ". ",
        { text: "The Dieline", href: "https://thedieline.com/eez-co-shifted-from-a-small-product-first-brand-to-a-bold-wellness-leader/" },
        " also covered the rebrand, which earned a Silver Dieline Award for brand identity system.",
      ],
    ],
    gallery: [
      { src: "/work/eez-co/01.webp", width: 750, height: 750 },
      { src: "/work/eez-co/02.webp", width: 750, height: 750 },
      { src: "/work/eez-co/03.png", width: 393, height: 398 },
      { src: "/work/eez-co/04.png", width: 370, height: 373 },
      { src: "/work/eez-co/05.jpg", width: 1600, height: 851 },
    ],
    role: ["Copy"],
    agency: { kind: "Agency", name: "Brains", href: "https://www.brains.co/" },
    team: [
      { role: "Copywriter", name: "Anusha Bansal", href: "https://www.anusha-bansal.com/" },
    ],
  },
  {
    slug: "doublesoul",
    title: "doublesoul",
    services: "Verbal identity • brand story • packaging • site copy",
    image: "/DOUBLESoul.webp",
    tint: "oklch(91% 0.055 49)",
    summary: "Here to clean up the world’s sock drawers, doublesoul designs ultra-cushioned socks, made sustainably.",
    body: [
      [
        "Here to clean up the world’s sock drawers, doublesoul designs ultra-cushioned socks, made sustainably. As a new brand breaking into a category that’s easy to overlook, doublesoul wanted to get people thinking about what’s going on underfoot and in the world.",
      ],
      [
        "I worked with ",
        { text: "Formal Studio", href: "https://formal-studio.com/DOUBLESOUL" },
        " to put words to the brand’s foundations and story, followed by messaging and guidelines for a casual, clear voice. Then it was on to site and packaging copy to pair with doublesoul’s bright, lo-fi visual system. When it comes to your socks, it’s easier than ever to tread (super) softly.",
      ],
    ],
    gallery: [
      { src: "/work/doublesoul/01.gif", width: 500, height: 500 },
      { src: "/work/doublesoul/02.gif", width: 500, height: 500 },
      { src: "/work/doublesoul/03.gif", width: 1533, height: 2297 },
      { src: "/work/doublesoul/04.gif", width: 1531, height: 2297 },
      { src: "/work/doublesoul/05.jpg", width: 2159, height: 1439 },
      { src: "/work/doublesoul/06.png", width: 590, height: 354 },
      { src: "/work/doublesoul/07.jpg", width: 750, height: 1125 },
      { src: "/work/doublesoul/08.jpg", width: 2400, height: 1600 },
    ],
    role: ["Copy"],
    agency: { kind: "Studio", name: "Formal Studio", href: "https://formal-studio.com/" },
    team: [
      { role: "Web design", name: "Lisa Meyer" },
    ],
  },
  {
    slug: "respin-health",
    title: "Respin Health",
    services: "Creative concepts • brand positioning • manifesto • verbal identity • messaging • site copy",
    image: "/respin.webp",
    tint: "oklch(91% 0.032 64)",
    summary: "Founded by actress Halle Berry, Respin Health is a community-based digital platform conceived as a thoughtful, empowering response to the confusion, fear, and loneliness so many women still face as they enter menopause.",
    body: [
      [
        "Founded by actress Halle Berry, Respin Health is a community-based digital platform conceived as a thoughtful, empowering response to the confusion, fear, and loneliness so many women still face as they enter menopause. Designed for every phase of menopause, it offers tailored coaching from vetted and credentialed experts.",
      ],
      [
        "Creative agency ",
        { text: "Established", href: "https://establishednyc.com/" },
        " developed every aspect of the brand; I joined for strategy and copy. I started by auditing the (now-booming) menopause space to understand the key players and how they speak, and where Respin Health fits. From there, I worked on the foundational brand pieces: articulating positioning and creative territories and creating verbal guidelines, manifesto, and key messaging. Respin Health’s launch was covered by outlets like ",
        { text: "Women’s Health", href: "https://www.womenshealthmag.com/health/a63352690/halle-berry-menopause-respin/" },
        ", ",
        { text: "TODAY", href: "https://www.today.com/video/halle-berry-on-advocating-for-menopause-care-second-acts-more-232244293726" },
        ", and ",
        { text: "WWD", href: "https://wwd.com/beauty-industry-news/wellness/halle-berry-respin-health-menopause-1236947001/" },
        ". You can view more of the Respin identity work from Established ",
        { text: "here", href: "https://establishednyc.com/re-spin-health" },
        ".",
      ],
    ],
    gallery: [
      { src: "/work/respin-health/01.png", width: 1226, height: 4362 },
    ],
    role: ["Strategy", "Copy"],
    agency: { kind: "Agency", name: "Established", href: "https://establishednyc.com/" },
  },
  {
    slug: "dame",
    title: "Dame",
    services: "Verbal identity • naming • newsletters • packaging • site copy • social",
    image: "/dame.webp",
    tint: "oklch(91% 0.055 43)",
    summary: "A courageous trailblazer in the world of sexual wellness, Dame thoughtfully designs vibrators and other products to encourage experimentation and play.",
    body: [
      [
        "A courageous trailblazer in the world of sexual wellness, Dame thoughtfully designs vibrators and other products to encourage experimentation and play. It originally launched with a mission of closing the pleasure gap and has since gone on to make headlines as an unapologetic proponent of pleasure for all.",
      ],
      [
        "In 2020, I collaborated with a creative team to refresh and evolve Dame’s visual and verbal identity, inspired by a new strategic proposition: pleasure is health. I created new guidelines to elevate Dame’s voice. This work led to two years as Dame’s go-to resource for campaigns, newsletters, social, packaging, naming, and site copy.",
      ],
    ],
    gallery: [
      { src: "/work/dame/01.jpg", width: 750, height: 878 },
      { src: "/work/dame/02.jpg", width: 750, height: 1790 },
      { src: "/work/dame/03.png", width: 1124, height: 720 },
      { src: "/work/dame/04.png", width: 594, height: 598 },
      { src: "/work/dame/05.jpg", width: 750, height: 862 },
      { src: "/work/dame/06.png", width: 992, height: 550 },
    ],
    hero: "/work/dame/06.png",
    role: ["Naming", "Copy"],
    agency: { kind: "Studio", name: "Formal Studio", href: "https://formal-studio.com/" },
    team: [
      { role: "Brand refresh strategy", name: "Gilian Rappaport", href: "https://www.gilianrappaport.space/" },
    ],
  },
  {
    slug: "little-spoon",
    title: "Little Spoon",
    services: "Naming • messaging • packaging • site copy",
    image: "/littlespoon.webp",
    tint: "oklch(91% 0.055 268)",
    summary: "Made for the modern parent—and their kids—Little Spoon creates childhood nutrition that’s tailored to developmental stages.",
    body: [
      [
        "Made for the modern parent—and their kids—Little Spoon creates childhood nutrition that’s tailored to developmental stages. As the brand expanded into lunches and snacks for the 4- to 7-year-old set, it tapped NYC agency ",
        { text: "Smakk Studios", href: "https://smakkstudios.com/little-spoon/" },
        " to “age up” its packaging and copy to match.",
      ],
      [
        "I collaborated with Smakk’s strategy and design team to launch junk-free products that are credible enough for parents to trust and cool enough for kids to show off in the lunchroom. I named products and flavors (making sure they were as fun to say as they are to eat) and wrote pack and site copy.",
      ],
      [
        "Per ",
        { text: "The Dieline", href: "https://thedieline.com/little-spoon-2/" },
        ", the new product line “sets a new standard for kids' lunches and snacks, bridging old-school charm with modern, playful aesthetics.⁠”",
      ],
    ],
    gallery: [
      { src: "/work/little-spoon/01.jpg", width: 2000, height: 2000 },
      { src: "/work/little-spoon/02.jpg", width: 750, height: 422 },
      { src: "/work/little-spoon/03.png", width: 750, height: 497 },
      { src: "/work/little-spoon/04.gif", width: 1624, height: 1624 },
      { src: "/work/little-spoon/05.jpg", width: 1536, height: 864 },
    ],
    role: ["Naming", "Copy"],
    agency: { kind: "Agency", name: "SMAKK Studios", href: "https://smakkstudios.com/work/little-spoon" },
  },
  {
    slug: "de-lune",
    title: "De Lune",
    services: "Verbal identity • brand story • product naming • packaging • site copy",
    image: "/delune.webp",
    tint: "oklch(91% 0.036 255)",
    summary: "De Lune is a pioneering company that offers research-backed, natural relief of period symptoms and menstrual health resources.",
    body: [
      [
        "De Lune is a pioneering company that offers research-backed, natural relief of period symptoms and menstrual health resources. They’re actively building a world where menstruation and period symptoms are no longer taboo. I worked with a strategic and creative team to refresh De Lune’s brand system, including a new tone of voice, site copy, and product naming. The result was an approachable yet sophisticated identity to take this groundbreaking brand into the new age of period health.",
      ],
    ],
    gallery: [
      { src: "/work/de-lune/01.png", width: 1000, height: 557 },
      { src: "/work/de-lune/02.png", width: 1000, height: 567 },
      { src: "/work/de-lune/03.png", width: 1000, height: 571 },
      { src: "/work/de-lune/04.png", width: 494, height: 745 },
      { src: "/work/de-lune/05.png", width: 496, height: 748 },
      { src: "/work/de-lune/06.png", width: 500, height: 498 },
      { src: "/work/de-lune/07.jpg", width: 500, height: 625 },
    ],
    role: ["Naming", "Copy"],
    agency: { kind: "Studio", name: "Formal Studio", href: "https://formal-studio.com/" },
    team: [
      { role: "Strategy", name: "Gilian Rappaport", href: "https://www.gilianrappaport.space/" },
      { role: "Web design", name: "No Ideas", href: "https://noideas.website/" },
    ],
  },
  {
    slug: "fair-harbor",
    title: "Fair Harbor",
    services: "Verbal identity • brand story • catalog • site copy",
    image: "/fairharbor.webp",
    tint: "oklch(91% 0.055 23)",
    summary: "Inspired by the laid-back barefoot Long Island community of the same name, Fair Harbor creates innovative, ultra-comfortable apparel made from upcycled plastic bottles, designed for the beach and beyond.",
    body: [
      [
        "Inspired by the laid-back barefoot Long Island community of the same name, Fair Harbor creates innovative, ultra-comfortable apparel made from upcycled plastic bottles, designed for the beach and beyond. A strong sense of place pervades the entire brand. It’s at once nostalgic and hopeful, working to safeguard the future so everyone can keep enjoying the places they love, too.",
      ],
      [
        "In collaboration with ",
        { text: "Formal Studio", href: "https://formal-studio.com/" },
        ", I built a relaxed, inviting tone of voice and crafted site copy as part of a full brand refresh. Fair Harbor’s signature mesh-free lining frees people to go about their days in total comfort, and the new branding embodies salt-kissed ease. After the brand work, I also partnered directly with Fair Harbor for several months on site copy, campaign landing pages, and catalog copy.",
      ],
    ],
    gallery: [
      { src: "/work/fair-harbor/01.png", width: 712, height: 293 },
      { src: "/work/fair-harbor/02.png", width: 500, height: 1285 },
      { src: "/work/fair-harbor/03.png", width: 499, height: 1811 },
      { src: "/work/fair-harbor/04.png", width: 750, height: 499 },
    ],
    role: ["Copy"],
    agency: { kind: "Studio", name: "Formal Studio", href: "https://formal-studio.com/" },
  },
  {
    slug: "wilderness-trail",
    title: "Wilderness Trail",
    services: "Site copy • brand story • blog posts",
    image: "/Wilderness.webp",
    tint: "oklch(91% 0.054 67)",
    summary: "Founded by two ex-bandmates known as “the science guys of bourbon,” Wilderness Trail is a small-batch whiskey company that combines time-honored distilling techniques with cutting-edge science to create seriously special bourbons and ryes.",
    body: [
      [
        "Founded by two ex-bandmates known as “the science guys of bourbon,” ",
        { text: "Wilderness Trail", href: "https://www.wildernesstraildistillery.com/" },
        " is a small-batch whiskey company that combines time-honored distilling techniques with cutting-edge science to create seriously special bourbons and ryes.",
      ],
      [
        "Now part of the Campari portfolio, Wilderness Trail needed a comprehensive new site to complement a recent identity refresh and a clear, cohesive story to entice and educate discerning drinkers. The big challenge was conveying the founders’ intense focus on craft, fermentation science, and the finer details without overwhelming the reader with TMI. I created site copy across all key pages and researched and wrote several blog posts investigating the brand’s history, its unique position in the wider whiskey world, and why rye is giving bourbon a run for its money.",
      ],
    ],
    gallery: [
      { src: "/work/wilderness-trail/01.png", width: 1202, height: 754 },
      { src: "/work/wilderness-trail/02.jpg", width: 2500, height: 8652 },
      { src: "/work/wilderness-trail/03.jpg", width: 2500, height: 8730 },
      { src: "/work/wilderness-trail/04.jpg", width: 2500, height: 7598 },
      { src: "/work/wilderness-trail/05.jpg", width: 2500, height: 5477 },
      { src: "/work/wilderness-trail/06.jpg", width: 2500, height: 5398 },
    ],
    role: ["Copy"],
    agency: { kind: "Agency", name: "DEBRAIN", href: "https://www.hellodebrain.com" },
  },
  {
    slug: "burts-bees",
    title: "Burt's Bees",
    services: "Verbal identity • site copy • emails • messaging",
    image: "/BurtsBees.webp",
    tint: "oklch(91% 0.055 85)",
    summary: "Burt’s Bees has long held a special place for those who remember tucking its yellow lip balm tins into their jean pockets.",
    body: [
      [
        "Burt’s Bees has long held a special place for those who remember tucking its yellow lip balm tins into their jean pockets. Founded over four decades ago by a pair of iconoclastic friends, the brand has always lived its mission of doing things better for people and the planet. Now it wanted to reach a new generation of conscious consumers and communicate the brand’s heritage and values in a more relatable, modern way. It tapped ",
        { text: "SMAKK Studios", href: "https://smakkstudios.com/burts-bees/" },
        " to give its site and digital voice a full makeover.",
      ],
      [
        "Along with copy for the redesigned site—including homepage, about us, product pages, and campaign landing pages—I created guidelines for how to write for web, social, newsletters, and SMS. This work freed the brand to be more energized and more fun everywhere it reached customers online. I also wrote welcome, transactional, and win-back emails that launched with the new site in 2023.",
      ],
    ],
    gallery: [
      { src: "/work/burts-bees/01.png", width: 750, height: 429 },
      { src: "/work/burts-bees/02.jpg", width: 500, height: 2191 },
      { src: "/work/burts-bees/03.jpg", width: 500, height: 1979 },
    ],
    role: ["Copy"],
    agency: { kind: "Agency", name: "SMAKK Studios", href: "https://smakkstudios.com/" },
  },
  {
    slug: "fur",
    title: "Fur",
    services: "Packaging • site copy",
    image: "/fur.webp",
    tint: "oklch(91% 0.054 94)",
    summary: "Fur is the first beauty brand dedicated to clean body hair care and head-to-toe soothing and smoothing for every part of the body—for everybody.",
    body: [
      [
        "Fur is the first beauty brand dedicated to clean body hair care and head-to-toe soothing and smoothing for every part of the body—for everybody.",
      ],
      [
        "When Fur launched, I wrote homepage copy, product descriptions, and packaging copy, all to convey the brand’s open-minded and thoughtful approach to self care and body hair acceptance.",
      ],
    ],
    gallery: [
      { src: "/work/fur/01.jpg", width: 750, height: 559 },
      { src: "/work/fur/02.png", width: 750, height: 559 },
      { src: "/work/fur/03.png", width: 750, height: 559 },
    ],
    role: ["Copy"],
    agency: { kind: "Studio", name: "Formal Studio", href: "https://formal-studio.com/" },
  },
  {
    slug: "targetbook",
    title: "Target: 20 Years of Design for All",
    services: "Articles • headlines • research",
    image: "/Target.webp",
    tint: "oklch(91% 0.055 25)",
    summary: "Target has always rejected the notion that great design should only be accessible to the few.",
    body: [
      [
        "Target has always rejected the notion that great design should only be accessible to the few. This open-minded approach paved the way for 180+ partnerships with renowned designers like Missoni, Isaac Mizrahi, Philippe Starck, Alexander McQueen, Lilly Pulitzer, and many more.",
      ],
      [
        "I worked with the team at Chandelier Creative to research and write headlines and columns for ",
        { text: "Target: 20 Years of Design for All", href: "https://www.rizzolibookstore.com/product/target-20-years-design-all-how-target-revolutionized-accessible-design" },
        ": How Target Revolutionized Accessible Design (Rizzoli), a book celebrating decades of these groundbreaking collaborations. The book is a beautiful design object in itself, with pages of colorful layouts, archival photographs, and interviews and stories.",
      ],
    ],
    gallery: [
      { src: "/work/targetbook/01.jpg", width: 750, height: 500 },
      { src: "/work/targetbook/02.jpg", width: 750, height: 500 },
      { src: "/work/targetbook/03.jpg", width: 750, height: 500 },
      { src: "/work/targetbook/04.jpg", width: 500, height: 750 },
      { src: "/work/targetbook/05.jpg", width: 750, height: 500 },
    ],
    role: ["Research", "Copy"],
    agency: { kind: "Agency", name: "Chandelier", href: "https://www.chandeliercreative.com/" },
    team: [
      { role: "Creative direction", name: "Marian Shelley Acuña", href: "https://marianshelleyacuna.com/" },
      { role: "Editor", name: "Laura Bannister", href: "http://laurabannister.com/" },
    ],
  },
  {
    slug: "pernod-ricard",
    title: "Pernod Ricard",
    services: "Site copy • blogs • banner ads • gift guides • newsletters • ads • social • scripts • crosswords",
    image: "/PernodRicard.webp",
    tint: "oklch(91% 0.050 112)",
    summary: "Pernod Ricard is a global leader in wine and spirits, with a portfolio spanning some of the bar’s most iconic bottles: Absolut, Jameson, Malibu, Kahlua, and many others.",
    body: [
      [
        { text: "Pernod Ricard", href: "https://www.pernod-ricard-usa.com/" },
        " is a global leader in wine and spirits, with a portfolio spanning some of the bar’s most iconic bottles: Absolut, Jameson, Malibu, Kahlua, and many others.",
      ],
      [
        "Working with DËBRAIN, Pernod’s digital AOR for several years, I wrote hundreds (I mean, hundreds) of newsletters across the company’s family of brands, plus countless campaign sites, gift guides, banner ads, digital billboards, social posts, video scripts—and even a series of crossword puzzles for The Glenlivet. Cheers.",
      ],
      [
        "Accounts: Aberlour, Absolut, Altos, Avion, Chivas Regal, Jameson, Kahlua, Malibu, Martell, Smithworks Vodka, The Glenlivet",
      ],
    ],
    gallery: [
      { src: "/work/pernod-ricard/01.png", width: 750, height: 695 },
      { src: "/work/pernod-ricard/02.png", width: 552, height: 434 },
      { src: "/work/pernod-ricard/03.png", width: 659, height: 534 },
      { src: "/work/pernod-ricard/04.png", width: 1500, height: 771 },
      { src: "/work/pernod-ricard/05.png", width: 750, height: 816 },
      { src: "/work/pernod-ricard/06.gif", width: 1000, height: 2920 },
      { src: "/work/pernod-ricard/07.jpg", width: 1000, height: 1742 },
      { src: "/work/pernod-ricard/08.png", width: 1124, height: 510 },
      { src: "/work/pernod-ricard/09.png", width: 1133, height: 421 },
      { src: "/work/pernod-ricard/10.jpg", width: 1302, height: 3110 },
      { src: "/work/pernod-ricard/11.jpg", width: 1302, height: 2826 },
      { src: "/work/pernod-ricard/12.png", width: 1339, height: 961 },
      { src: "/work/pernod-ricard/13.png", width: 1339, height: 2851 },
      { src: "/work/pernod-ricard/14.png", width: 2500, height: 1167 },
      { src: "/work/pernod-ricard/15.png", width: 2500, height: 1787 },
      { src: "/work/pernod-ricard/16.png", width: 2500, height: 1894 },
      { src: "/work/pernod-ricard/17.png", width: 1096, height: 776 },
    ],
    role: ["Copy"],
    agency: { kind: "Agency", name: "DEBRAÏN", href: "https://hellodebrain.com/" },
  },
  {
    slug: "tabitha-brown-target",
    title: "Tabitha Brown for Target",
    services: "Magazine copy • copyediting",
    image: "/TabithaBrownForTarget_02.webp",
    tint: "oklch(91% 0.055 40)",
    summary: "From 2022 to 2023, Target partnered with beloved actress and social media personality Tabitha Brown on four exclusive limited-run lines of home decor, food, and more.",
    body: [
      [
        "From 2022 to 2023, Target partnered with beloved actress and social media personality Tabitha Brown on four ",
        { text: "exclusive limited-run lines", href: "https://www.target.com/c/tabitha-brown-for-target/-/N-3k8lx" },
        " of home decor, food, and more. NYC agency Mythology created four issues of TAB Mag—a joyful celebration of Tabitha’s favorite things—to go with each release.",
      ],
      [
        "I worked with the creative team at Mythology on copy for the fourth issue of TAB Mag, which was focused on easy, breezy ideas for outdoor hosting. I also copyedited issues two through four, making sure each was polished and ready for print.",
      ],
    ],
    gallery: [
      { src: "/work/tabitha-brown-target/01.png", width: 589, height: 784 },
      { src: "/work/tabitha-brown-target/02.png", width: 595, height: 779 },
      { src: "/work/tabitha-brown-target/03.png", width: 584, height: 777 },
      { src: "/work/tabitha-brown-target/04.png", width: 1183, height: 739 },
      { src: "/work/tabitha-brown-target/05.png", width: 1182, height: 757 },
      { src: "/work/tabitha-brown-target/06.png", width: 1184, height: 777 },
    ],
    role: ["Copy", "Copyediting"],
    agency: { kind: "Agency", name: "Mythology", href: "https://www.mythology.com" },
  },
];
